version: '3'
services:
  ros1-main-program:
    build: 
      context: .  
      dockerfile: Dockerfile
    image: pomelo925/realsense-noetic-root:pcl
    container_name: diff-build
    tty: true
    privileged: true
    network_mode: host

    working_dir: /home/user/main_ws/src
    environment:
      - DISPLAY=${DISPLAY}  # Turn on MOBAXTERM first
      - XAUTHORITY=/root/.Xauthority   # Set Xauthority path

    volumes:
      - ../extraction-ws:/home/extraction-ws
      - ../startup:/home/startup

    command: /bin/bash -c "cd /home/user/main_ws && source devel/setup.bash && catkin_make && echo 'done make'"