// Generated by gencpp from file yolo/ready.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_READY_H
#define YOLO_MESSAGE_READY_H

#include <ros/service_traits.h>


#include <yolo/readyRequest.h>
#include <yolo/readyResponse.h>


namespace yolo
{

struct ready
{

typedef readyRequest Request;
typedef readyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ready
} // namespace yolo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yolo::ready > {
  static const char* value()
  {
    return "da5a7aac6c5f3883c2c81418dc34dfa3";
  }

  static const char* value(const ::yolo::ready&) { return value(); }
};

template<>
struct DataType< ::yolo::ready > {
  static const char* value()
  {
    return "yolo/ready";
  }

  static const char* value(const ::yolo::ready&) { return value(); }
};


// service_traits::MD5Sum< ::yolo::readyRequest> should match
// service_traits::MD5Sum< ::yolo::ready >
template<>
struct MD5Sum< ::yolo::readyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yolo::ready >::value();
  }
  static const char* value(const ::yolo::readyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo::readyRequest> should match
// service_traits::DataType< ::yolo::ready >
template<>
struct DataType< ::yolo::readyRequest>
{
  static const char* value()
  {
    return DataType< ::yolo::ready >::value();
  }
  static const char* value(const ::yolo::readyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yolo::readyResponse> should match
// service_traits::MD5Sum< ::yolo::ready >
template<>
struct MD5Sum< ::yolo::readyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yolo::ready >::value();
  }
  static const char* value(const ::yolo::readyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo::readyResponse> should match
// service_traits::DataType< ::yolo::ready >
template<>
struct DataType< ::yolo::readyResponse>
{
  static const char* value()
  {
    return DataType< ::yolo::ready >::value();
  }
  static const char* value(const ::yolo::readyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOLO_MESSAGE_READY_H
