// Generated by gencpp from file yolo/signalRequest.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_SIGNALREQUEST_H
#define YOLO_MESSAGE_SIGNALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo
{
template <class ContainerAllocator>
struct signalRequest_
{
  typedef signalRequest_<ContainerAllocator> Type;

  signalRequest_()
    : signal(0)  {
    }
  signalRequest_(const ContainerAllocator& _alloc)
    : signal(0)  {
  (void)_alloc;
    }



   typedef int64_t _signal_type;
  _signal_type signal;





  typedef boost::shared_ptr< ::yolo::signalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo::signalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct signalRequest_

typedef ::yolo::signalRequest_<std::allocator<void> > signalRequest;

typedef boost::shared_ptr< ::yolo::signalRequest > signalRequestPtr;
typedef boost::shared_ptr< ::yolo::signalRequest const> signalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo::signalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo::signalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo::signalRequest_<ContainerAllocator1> & lhs, const ::yolo::signalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.signal == rhs.signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo::signalRequest_<ContainerAllocator1> & lhs, const ::yolo::signalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo::signalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo::signalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::signalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::signalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::signalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::signalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo::signalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e57ff88f4c17b249531e77b7e8959fdc";
  }

  static const char* value(const ::yolo::signalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe57ff88f4c17b249ULL;
  static const uint64_t static_value2 = 0x531e77b7e8959fdcULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo::signalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo/signalRequest";
  }

  static const char* value(const ::yolo::signalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo::signalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# onboard cam Service\n"
"int64 signal\n"
;
  }

  static const char* value(const ::yolo::signalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo::signalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo::signalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo::signalRequest_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    Printer<int64_t>::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_MESSAGE_SIGNALREQUEST_H
