// Generated by gencpp from file yolo/signal.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_SIGNAL_H
#define YOLO_MESSAGE_SIGNAL_H

#include <ros/service_traits.h>


#include <yolo/signalRequest.h>
#include <yolo/signalResponse.h>


namespace yolo
{

struct signal
{

typedef signalRequest Request;
typedef signalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct signal
} // namespace yolo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yolo::signal > {
  static const char* value()
  {
    return "f949f7237e30347573901ebcc4b2ea5e";
  }

  static const char* value(const ::yolo::signal&) { return value(); }
};

template<>
struct DataType< ::yolo::signal > {
  static const char* value()
  {
    return "yolo/signal";
  }

  static const char* value(const ::yolo::signal&) { return value(); }
};


// service_traits::MD5Sum< ::yolo::signalRequest> should match
// service_traits::MD5Sum< ::yolo::signal >
template<>
struct MD5Sum< ::yolo::signalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yolo::signal >::value();
  }
  static const char* value(const ::yolo::signalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo::signalRequest> should match
// service_traits::DataType< ::yolo::signal >
template<>
struct DataType< ::yolo::signalRequest>
{
  static const char* value()
  {
    return DataType< ::yolo::signal >::value();
  }
  static const char* value(const ::yolo::signalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yolo::signalResponse> should match
// service_traits::MD5Sum< ::yolo::signal >
template<>
struct MD5Sum< ::yolo::signalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yolo::signal >::value();
  }
  static const char* value(const ::yolo::signalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yolo::signalResponse> should match
// service_traits::DataType< ::yolo::signal >
template<>
struct DataType< ::yolo::signalResponse>
{
  static const char* value()
  {
    return DataType< ::yolo::signal >::value();
  }
  static const char* value(const ::yolo::signalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOLO_MESSAGE_SIGNAL_H
