// Generated by gencpp from file yolo/yolomsg.msg
// DO NOT EDIT!


#ifndef YOLO_MESSAGE_YOLOMSG_H
#define YOLO_MESSAGE_YOLOMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolo
{
template <class ContainerAllocator>
struct yolomsg_
{
  typedef yolomsg_<ContainerAllocator> Type;

  yolomsg_()
    : x()
    , y()  {
    }
  yolomsg_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::yolo::yolomsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolo::yolomsg_<ContainerAllocator> const> ConstPtr;

}; // struct yolomsg_

typedef ::yolo::yolomsg_<std::allocator<void> > yolomsg;

typedef boost::shared_ptr< ::yolo::yolomsg > yolomsgPtr;
typedef boost::shared_ptr< ::yolo::yolomsg const> yolomsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolo::yolomsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolo::yolomsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolo::yolomsg_<ContainerAllocator1> & lhs, const ::yolo::yolomsg_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolo::yolomsg_<ContainerAllocator1> & lhs, const ::yolo::yolomsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolo::yolomsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolo::yolomsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::yolomsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolo::yolomsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::yolomsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolo::yolomsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolo::yolomsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "462ac0ba687f22c2e73c0ec0413e0202";
  }

  static const char* value(const ::yolo::yolomsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x462ac0ba687f22c2ULL;
  static const uint64_t static_value2 = 0xe73c0ec0413e0202ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolo::yolomsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolo/yolomsg";
  }

  static const char* value(const ::yolo::yolomsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolo::yolomsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] x\n"
"float32[] y\n"
;
  }

  static const char* value(const ::yolo::yolomsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolo::yolomsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yolomsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolo::yolomsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolo::yolomsg_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLO_MESSAGE_YOLOMSG_H
